### ISSUE TITLE
Ask `Add after` for every map entry

### ISSUE THREAD

**Issue by kldzj** [kldzj/pzmod#10]
> In case of map mods, make user choose if they want the map mod and the map priority, even if the mod has only 1 entry. Some map mods are to be placed after or before others.
> 
> This way it should only ask to install mods that have more than 1 entry or mods that are maps themselves.

Copied from #6.

**Comment by laredson** [comment]
carhouse and other mods require max priority, that means first on list.
Muldraug must be last on list to be overwritten.
Therefore you may set maps to be before, not after, as priority is reversed.

There's a few exceptions that need to be placed first (top priority), they are:
basements, carhouse, carhouse2, interiorRV and those that use exterior tiles.
