### ISSUE TITLE
feat: list mod used disk

### ISSUE THREAD

**Issue by laredson** [kldzj/pzmod#14]
**Is your feature request related to a problem? Please describe.**
Not really a problem, just a desired addon

**Describe the solution you'd like**
I'd like the mod to generate a list of each mod sorting it by disk size. I suppose you have to make user insert a correct folder if they're not using standard c:\steam\steamapps...

**Describe alternatives you've considered**
I don't think there's any. I'm using a free server which moves 10gb max hdd for my tests, I need it to fit in 10gb, even if I have to put out some high sized mods like true music, which is not need to be tested.
Maybe a "max hdd size" option that makes you aware of the size of the server, but I think the list would be okay

**Additional context**
I'm using the program "Treesize" to see what are huge mods, but the program lists all my mods, not only the server ones

![image](https://github.com/kldzj/pzmod/assets/131942306/f2897edf-0907-4ddc-9b8d-e6fce0b5e487)

**Comment by kldzj** [comment]
I think the best I could do is calculating with the item size provided by the Workshop API. This would not include any changes the mod could make to your file system though.

**Comment by laredson** [comment]
> I think the best I could do is calculating with the item size provided by the Workshop API. This would not include any changes the mod could make to your file system though.

It's perfect if the API provides that info! I thought it didn't...

**Comment by kldzj** [comment]
Hey, this has been added in [v2.0.1](https://github.com/kldzj/pzmod/releases/tag/v2.0.1).

At the moment this is still quite rudimentary while I'm still figuring out where to store config instance specific settings. If I manage to find a good solution I will implement some kind of max size setting that will trigger warnings when you go near/over the limit.
