### ISSUE TITLE
Suddenly stopped working

### ISSUE THREAD

**Issue by laredson** [kldzj/pzmod#2]
I got an issue on my server, a mod I was using has disappeared from steam. In my way to find this, I tried to log in pzmod (as I use to do for mod changes on the server ini) but when I try to open it, just crashed.
Since then it won't read any ini, besides I manually removed the missing one and the server is running fine.

Maybe I should delete other files this program saves somewhere?

![image](https://user-images.githubusercontent.com/131942306/235415319-b3a9f907-fb7e-4734-9ae7-a503d39e8dbf.png)

**Comment by kldzj** [comment]
Thanks for reporting this issue. For now you can try to find and remove the offending mod id manually from the `WorkshopItems` list.

I'll soon roll out an update that will ask you if you want that mod to be removed.

**Comment by kldzj** [comment]
I just released [v1.0.3](https://github.com/kldzj/pzmod/releases/tag/v1.0.3) which should no longer crash but instead outputs a warning, letting you know which mod(s) caused this error. Let me know if you are still seeing problems.

Please note that pzmod does not auto-update, you'll have to download the new binary and replace the old one with it.

**Comment by laredson** [comment]
Yes! It worked! Thank you!

The prompt show 2 mods "I would like to remove". When I reached the list to find them, there was not any of both.
The thing is I had other mod saying "requires" the "missing" mods. It worked fine anyways without those mods... but workshop is marked as required even not actually really required.

**Comment by kldzj** [comment]
> The prompt show 2 mods "I would like to remove". When I reached the list to find them, there was not any of both.

Sorry about that, I'll have to fix that. Just read it as 'Mod could not be fetched and is going to be removed' for now.

> The thing is I had other mod saying "requires" the "missing" mods. It worked fine anyways without those mods... but workshop is marked as required even not actually really required.

Not much I can do about that I fear, any `pzmod` user should be wary, as it can be only as good as the data it's getting from the Workshop.

**Comment by laredson** [comment]
Yes, this issue is not happening that much... and your fix is perfect because it works anyways. I could just not quit that mod because I know is working without the requirements, but I wanted to remove it anyways because is OP

One suggestion / petition if its allowed (idk if I can put it somewhere else):
It would be AWESOME if your mod captures a mod collection and adds all of the items from it. 
That would become zomboid modding really agile and easy.

**Comment by kldzj** [comment]
> It would be AWESOME if your mod captures a mod collection and adds all of the items from it.

Definitely have thought about that. I will look into it, I just can't make any promises on an ETA right now.

You're welcome to create more issues for bugs or feature suggestions. :)

**Comment by laredson** [comment]
Oh nice! So you had it into your roadmap 😂 

hahaha you know, we always want everything "right now" don't we?
I'm really thankful already for this program. This makes modding more enjoyable, very useful!
I'm double thankful for currently know you are on it!
Tripled when it's working 😃 

For an issue... should I start a new one?

The program is not adding the "Map=" names. This should be done for maps, spawns and some other kind of mods.
It is marked as "Map Folder:" in the list. For example:

Workshop ID: 2971265728
Mod ID: ExhibitionCircuit
Map Folder: ExhibitionCircuit

It sometimes has the same name in the map folder. As far as I know this should be relatively easy to implement. 👌

**Comment by kldzj** [comment]
That's a great idea and shouldn't take too much work to get it to work. But yeah, please create a new issue so I can keep better track of it. :)

Thanks a bunch for the feedback!

**Comment by laredson** [comment]
Anytime!
If you want some other test of feedback on anything just tell
