### ISSUE TITLE
Map Folder: -> Map=

### ISSUE THREAD

**Issue by laredson** [kldzj/pzmod#3]
The program is not adding the "Map=" names. This should be done for maps, spawns and some other kind of mods.
It is marked as "Map Folder:" in the list. For example:

Workshop ID: 2971265728
Mod ID: ExhibitionCircuit
Map Folder: ExhibitionCircuit

**Comment by kldzj** [comment]
Hey @laredson, I just [pre-released v2](https://github.com/kldzj/pzmod/releases/tag/v2.0.0-next.0), would you mind testing it a bit and providing feedback?

**Comment by laredson** [comment]
I'm on it, just downloaded. Do I report tests here?

**Comment by kldzj** [comment]
Thanks! If it's specific issues please be so kind to create a new issue :)
