### ISSUE TITLE
Windows: Cannot paste Steam API key

### ISSUE THREAD

**Issue by laredson** [kldzj/pzmod#5]
For some reason it doesn't let me right click to paste in CMD
Last version actually paste it and makes it invisible, but this one just don't do anything when right click on API menu. In normal menu is working as usual...

I had to add it by hand typing and it worked. Appears * for each num/letter.
Would be nice to have it show ********************** when you paste using right click

**Comment by kldzj** [comment]
Thanks, I'll take a look at it using the windows version. In the meantime, does `Ctrl`+`Shift`+`V` work for you?

**Comment by laredson** [comment]
Somehow it worked using the right click

I've been pressing right click and Ctrl+Shift+V several times, also checked the ? option and tried to do it again, nothing worked until in a moment, for no reason, start working.

Too weird...

**Comment by kldzj** [comment]
I cannot reproduce this issue. :/

> Somehow it worked using the right click

Meaning it's working for you now?

**Comment by laredson** [comment]
Yes. As I explain, is too weird, but it suddenly started working
