### ISSUE TITLE
Prompt user if mod ids could not be parsed

### ISSUE THREAD

**Issue by laredson** [kldzj/pzmod#7]
![image](https://github.com/kldzj/pzmod/assets/131942306/229bdcb6-4985-4bfa-ab5d-b8996455a2af)

![image](https://github.com/kldzj/pzmod/assets/131942306/f912b3d0-05d4-492f-869a-cfb5eeaafad3)

There are some particular cases in which workshop doesn't detect the mod. For some reason...
Maybe this would be solved here by adding a manual prompt:

WARNING Parsed workshop item has no mods
Would you like to enter ModID manually? (y/n)

**Comment by kldzj** [comment]
Good idea, I'll look into that. :)

**Comment by kldzj** [comment]
Thanks a lot for raising this issue, I implemented your suggestion. You can update using `pzmod update`.
