### ISSUE TITLE
.NET windows integration

### ISSUE THREAD

**Issue by laredson** [kldzj/pzmod#8]
I've been working with C# and other languages in .NET
As far as I know, it should be easy to integrate the code in a windows app to make it more user-friendly 

Not an issue, more a proposal. I'd make the windows app leaving it "empty" for your code to be set in

**Comment by kldzj** [comment]
Theoretically that could be possible, using `cgo` to export shared libs, but that would require some changes in the Go code that I can't quite foresee yet (really depends on which parts of the code you'd want to make use of).

At that point though you'd pretty much only be benefitting from the workshop calls, the config file parser and a rudimentary config class.

I'll close this issue for now, but feel free to investigate this more and post your findings here. :)

**Comment by laredson** [comment]
I just think it would be next step. It is working very nice now, thus is not very known. 
You could probably post this in nexus or other modding platforms to earn some money from just downloads once you feel it's time to release. This will help a lot of server-runners. But if this evolves to a windows app, and make it work for single and multiplayer, it would be massively used... the indie stone interface is... you know... not as good as we could expect
.NET is very easy to learn and use, so maybe you'd like to get into it. Also unity is a good choice for a windows environment app

Zomboid has not a "good" mod manager program as other titles have, like mod organizer for fallout 4, mod engine for darksouls 3 and elden ring
In any case, awesome this is working so good!

**Comment by kldzj** [comment]
> .NET is very easy to learn and use, so maybe you'd like to get into it

I am experienced with C#, it's just that personally I need to run this on a GUI-less linux server. I will be thinking about bringing a Windows GUI version using some Go GUI lib.
